name: Build

on:
  push:
    branches: [ custom-engine ]
  pull_request:
    branches: [ custom-engine ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    #
    # Install vcpkg + dependencies
    #
    - name: Install dependencies
      shell: cmd
      run: |

        echo Installing vcpkg...

        git clone https://github.com/microsoft/vcpkg.git NoxCore\vendors\vcpkg

        cd NoxCore\vendors\vcpkg

        bootstrap-vcpkg.bat

        cd ..\..\..

        echo Installing packages...

        NoxCore\vendors\vcpkg\vcpkg.exe install ^
          sdl3[vulkan] ^
          glm ^
          entt ^
          spdlog ^
          xxhash ^
          yaml-cpp ^
          box2d ^
          imguizmo ^
          freetype ^
          skia ^
          stb ^
          ktx[vulkan] ^
          tinyobjloader ^
          --triplet=x64-windows

    #
    # Install Slang
    #
    - name: Install Slang
      shell: cmd
      run: |

        set SLANG_VERSION=2026.13

        curl -L ^
        https://github.com/shader-slang/slang/releases/download/v%SLANG_VERSION%/slang-%SLANG_VERSION%-windows-x86_64.zip ^
        -o slang.zip


        mkdir NoxCore\vendors\slang


        tar -xf slang.zip -C NoxCore\vendors\slang


        del slang.zip
    #
    # Configure exactly like your bat file
    #
    - name: Configure CMake
      shell: cmd
      run: |

        cmake -S . -B build ^
        -G "Visual Studio 18 2026" ^
        -T ClangCL ^
        -A x64 ^
        -DCMAKE_TOOLCHAIN_FILE=NoxCore\vendors\vcpkg\scripts\buildsystems\vcpkg.cmake

    #
    # Build
    #
    - name: Build
      shell: cmd
      run: |
        cmake --build build --config Release
