name: Build

on:
  push:
    branches: [ custom-engine ]
  pull_request:
    branches: [ custom-engine ]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v7
      with:
          submodules: recursive

    #
    # Cache vcpkg
    #
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          NoxCore/vendors/vcpkg
        key: windows-vcpkg-${{ hashFiles('NoxCore/**') }}
        restore-keys: |
          windows-vcpkg-


    #
    # Install vcpkg + packages
    #
    - name: Install dependencies
      shell: cmd
      run: |

        echo ==== Clone vcpkg ====

        if not exist NoxCore\vendors\vcpkg (
            git clone https://github.com/microsoft/vcpkg.git NoxCore\vendors\vcpkg
        )


        echo ==== Bootstrap ====

        cd NoxCore\vendors\vcpkg

        if not exist vcpkg.exe (
            call bootstrap-vcpkg.bat
        )

        if errorlevel 1 exit /b 1


        echo ==== vcpkg version ====

        vcpkg.exe version


        cd ..\..\..



        echo ==== Install packages ====

        NoxCore\vendors\vcpkg\vcpkg.exe install ^
          sdl3[vulkan] ^
          glm ^
          entt ^
          spdlog ^
          xxhash ^
          yaml-cpp ^
          box2d ^
          imguizmo ^
          freetype ^
          skia ^
          stb ^
          ktx[vulkan] ^
          tinyobjloader ^
          --triplet=x64-windows


        if errorlevel 1 exit /b 1



    #
    # Verify
    #
    - name: Verify vcpkg
      shell: cmd
      run: |

        NoxCore\vendors\vcpkg\vcpkg.exe list

        dir NoxCore\vendors\vcpkg\installed\x64-windows\share\sdl3



    #
    # Cache Vulkan SDK
    #
    - name: Cache Vulkan SDK
      id: vulkan-cache
      uses: actions/cache@v4
      with:
        path: C:\VulkanSDK
        key: windows-vulkan-sdk-1.4.350



    #
    # Install Vulkan SDK
    #
    - name: Install Vulkan SDK
      if: steps.vulkan-cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: |

        $version = "1.4.350.0"

        $url = "https://sdk.lunarg.com/sdk/download/$version/windows/VulkanSDK-$version-Installer.exe"

        Invoke-WebRequest `
          -Uri $url `
          -OutFile VulkanSDK.exe


        Start-Process `
          -FilePath VulkanSDK.exe `
          -ArgumentList "--accept-licenses --default-answer --confirm-command install" `
          -Wait



    #
    # Setup Vulkan variables
    #
    - name: Setup Vulkan environment
      shell: pwsh
      run: |

        $version = "1.4.350.0"

        echo "VULKAN_SDK=C:\VulkanSDK\$version" >> $env:GITHUB_ENV
        echo "Vulkan_INCLUDE_DIR=C:\VulkanSDK\$version\Include" >> $env:GITHUB_ENV
        echo "Vulkan_LIBRARY=C:\VulkanSDK\$version\Lib\vulkan-1.lib" >> $env:GITHUB_ENV



    #
    # Install Slang
    #
    - name: Install Slang
      shell: cmd
      run: |

        set SLANG_VERSION=2026.13

        curl -L ^
        https://github.com/shader-slang/slang/releases/download/v%SLANG_VERSION%/slang-%SLANG_VERSION%-windows-x86_64.zip ^
        -o slang.zip


        mkdir NoxCore\vendors\slang


        tar -xf slang.zip -C NoxCore\vendors\slang


        del slang.zip



    #
    # Configure
    #
    - name: Configure CMake
      shell: cmd
      run: |

        cmake -S . -B build ^
        -G "Visual Studio 18 2026" ^
        -T ClangCL ^
        -A x64 ^
        -DCMAKE_TOOLCHAIN_FILE=NoxCore\vendors\vcpkg\scripts\buildsystems\vcpkg.cmake ^
        -DVulkan_INCLUDE_DIR=%Vulkan_INCLUDE_DIR% ^
        -DVulkan_LIBRARY=%Vulkan_LIBRARY%



    #
    # Build
    #
    - name: Build
      shell: cmd
      run: |

        cmake --build build --config Release
